In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [24]:
np.random.randn(8)

array([-0.56206715, -0.79159299,  1.09029231, -0.36005189,  0.70223018,
        0.77537783,  0.64165214,  2.09827612])

In [25]:
np.random.randn(4,4)

array([[ 1.27045912, -0.20260367,  0.65700563,  1.88566584],
       [-1.82973105,  0.25289517, -0.81618575, -1.59799368],
       [ 1.78765522, -0.21697736, -0.441222  , -0.76934005],
       [-0.92479667,  1.50146413,  1.01637898, -1.22514732]])

In [32]:
np.random.randint(1,10) #(a,b) a:başlangıç değeri , b:son değer(dahil değil)

5

In [34]:
np.random.randint(1,300,5) #(a,b,c) a:başlangıç değeri , b:son değer(dahil değil) , c:rastgele kaç adet sayı istediğimiz değer

array([ 76, 167, 232, 250,  99])

In [35]:
benimNumpyDizim = np.arange(30)

In [36]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
benimRandomDizim = np.random.randint(0,100,20)

In [40]:
benimRandomDizim

array([77, 85, 15, 52, 57, 22, 24, 95, 27, 87, 65, 94, 11, 27, 87,  8, 88,
       89, 91, 19])

## numpy dizi methodları

In [41]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
benimNumpyDizim.max()

29

In [43]:
benimRandomDizim.max()

95

In [44]:
benimRandomDizim.min()

8

In [45]:
benimRandomDizim.argmax() #en büyük sayının indexini verir

7

In [47]:
benimRandomDizim.argmin() #en küçük sayının indexini verir

15

In [51]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [52]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])